### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by ziyaddin** [SabinaTalibova/Weather-App#2]
Documentation needs to be improved. We can add a description, installation steps and so on.

**Comment by SabinaTalibova** [comment]
this is just rough beginning. I am planning to write documentation once it is ready)
It just reads name of city and prints temperature. I was practicing working with API and pyhton
PS: I wrote this by just googling "how to...?" )

**Comment by ziyaddin** [comment]
It's great! I will try to contribute to code and documentation in my free time.

**Comment by SabinaTalibova** [comment]
Thanks a lot .  I am also planning to work on it after midterms)
